language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_script:
- sh -c "composer install --dev --no-progress"

script: cd application/tests;phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
